# Simple example of an !3 api deployment using docker-compose
# Please note: There is also a more advanced example in the main repository available
# https://github.com/not-three/main#deployment

services:
  app:
    image: ghcr.io/not-three/api:latest
    ports:
      - 3000:3000
    volumes:
      - db:/data/db

volumes:
  db:
