# This file is for local development only.
# It is not used, nor recommended, for production.

services:
  app:
    image: undefined
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CORS_ENABLED: true
      NODE_ENV: development
    volumes:
      - ./db:/app/db

volumes: {}
