name: Build and Publish Nightly

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".vscode/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: api
          tags: nightly,${{ github.sha }}
          registry: ghcr.io
          directory: ./
          dockerfile: ./Dockerfile
          addLatest: false
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Documentation
        run: pnpm build:docs

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: nightly
          publish_branch: docs

      - name: Send webhook to servers
        run: "curl -H \"Authorization: Bearer ${{ secrets.PORTAINER_WEBHOOK_SECRET }}\" ${{ secrets.PORTAINER_WEBHOOK_URL }}"
