name: Build and Publish Release

on:
  release:
    types: [ "created" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Replace version in package.json to be semver compatible
        run: sed -i "s/IN-DEV/$(echo $GITHUB_REF | sed 's/refs\/tags\///')/" package.json

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          tags: latest,${{ github.sha }},${{ github.ref_name }}
          image: api
          registry: ghcr.io
          directory: ./
          dockerfile: ./Dockerfile
          addLatest: false
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Documentation
        run: pnpm build:docs

      - name: Publish Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: docs
          clean-exclude: nightly/

      - name: Send webhook to servers
        run: "curl -H \"Authorization: Bearer ${{ secrets.PORTAINER_WEBHOOK_SECRET }}\" ${{ secrets.PORTAINER_WEBHOOK_URL }}"
